export const searchConstants = {
  FETCH_POPULAR_MOVIE_SUCCESS: "FETCH_POPULAR_MOVIE_SUCCESS",
  FETCH_POPULAR_MOVIE_FAILURE: "FETCH_POPULAR_MOVIE_FAILURE",
  FETCH_POPULAR_TV_SUCCESS: "FETCH_POPULAR_TV_SUCCESS",
  FETCH_POPULAR_TV_FAILURE: "FETCH_POPULAR_TV_FAILURE",
  FETCH_TRENDING_SUCCESS: "FETCH_TRENDING_SUCCESS",
  FETCH_TRENDING_FAILURE: "FETCH_TRENDING_FAILURE",
};
